### ISSUE TITLE
Noise background dilemma

### ISSUE THREAD

**Issue by m3ggle** [m3ggle/personal-portfolio#17]
The noise svg is already created but the implementation in the rest of the code is tricky to say the least.

Problem: when i use it for example in the footer component as a background it wont cover the whole component width and height because it retains it aspect ratio of 400x400 (screen: 1440x1024). When using `preserveAspectRatio="none"` on the svg then it works and covers the whole component while looking good but when using it it on a longer component like project showcase it covers it but looks terrible. 

"Solutions":
- tile/repeat the noise background so it keeps its ratio and covers the whole component. The following is a snippet from the conversation with chatGPT
Tiling the SVG is definitely an option that you can consider to make it cover the whole background without distorting the aspect ratio. Here's one way to achieve this:
---
Tiling the SVG is definitely an option that you can consider to make it cover the whole background without distorting the aspect ratio. Here's one way to achieve this:

1. Wrap the SVG element with a <div> element that has the same width and height as the container element, and set its position property to absolute.
```html
<div id="element1" style="position:relative;width:100%;height:fit-content;">
  <div id="element2" style="position:absolute;width:100%;height:100%;">
    <div id="element3-wrapper" style="position:absolute;width:100%;height:100%;">
      <svg id="element3" viewBox="0 0 400 400" xmlns="http://www.w3.org/2000/svg">
        <!-- SVG content goes here -->
      </svg>
    </div>
  </div>
  <div id="element4"></div>
</div>
```
2. Set the background-image CSS property of the element2 to the url() of a data URL created from the SVG element, and set its background-repeat property to repeat.
```css
#element2 {
  position: absolute;
  width: 100%;
  height: 100%;
  background-image: url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 400 400'>...</svg>");
  background-repeat: repeat;
}
```
3. Hide the SVG element by setting its display property to none.
```css 
#element3 {
  display: none;
}
```
This way, the SVG element is used to generate a data URL, which is used as the background image of the element2. The repeat value of the background-repeat property ensures that the image is tiled to cover the entire background, without distorting the aspect ratio. The element3 is hidden, since it's no longer needed.

Note that using a data URL as the background image can increase the page size and loading time, especially if the SVG is large or if there are multiple instances of the background on the page. In that case, you may want to consider using a separate image file instead.
---
